SELECT E.VOTER_ID_ORG, V.CITY, PARTY, BIRTH_DATE, 
ELECTION, VOTED,MEN, WOMEN, CG.TOTAL_POPULATION,
HISPANIC, WHITE, BLACK, NATIVE, ASIAN,PACIFIC
FROM ELECTIONS E
JOIN (SELECT * FROM VOTERS  LIMIT  10000) V  ON E.VOTER_ID_ORG = V.VOTER_ID_ORG 
JOIN CENSUS_TO_CITY CC ON V.CITY = CC.CITY
JOIN CENSUS_GENDER CG ON CC.CENSUSTRACT = CG.CENSUSTRACT
JOIN CENSUS_ETHNICITY CE ON CC.CENSUSTRACT = CE.CENSUSTRACT;



SELECT  V.CITY, PARTY, ELECTION, sum(case when VOTED = 'Y' Then 1 end) Voted_CNT,
sum(case when VOTED = 'N' Then 1 end) NOT_Voted_CNT,
sum(distinct CG.TOTAL_POPULATION) TOTAL_POPULATION--,
--MEN, WOMEN, 
--HISPANIC, WHITE, BLACK, NATIVE, ASIAN,PACIFIC
FROM ELECTIONS E
JOIN (SELECT * FROM VOTERS  LIMIT  10000) V  ON E.VOTER_ID_ORG = V.VOTER_ID_ORG 
JOIN CENSUS_TO_CITY CC ON V.CITY = CC.CITY
JOIN CENSUS_GENDER CG ON CC.CENSUSTRACT = CG.CENSUSTRACT
JOIN CENSUS_ETHNICITY CE ON CC.CENSUSTRACT = CE.CENSUSTRACT
GROUP BY V.CITY, PARTY, ELECTION;
